-- 0105: 업무 메모 + 일정 알림 (docs/memo-schedule-spec.md)
--   tb_memo / tb_user_schedule 신설 + 보고서 그룹 메뉴 M005-3, M005-4 등록
-- 롤백:
--   DELETE FROM tb_auth_menu WHERE menu_idn IN ('M005-3','M005-4');
--   DELETE FROM tb_menu WHERE menu_idn IN ('M005-3','M005-4');
--   DROP TABLE IF EXISTS tb_user_schedule;
--   DROP TABLE IF EXISTS tb_memo;

-- 1) 업무 메모
CREATE TABLE IF NOT EXISTS tb_memo (
  region     varchar(20) NOT NULL,
  memo_idn   bigint GENERATED BY DEFAULT AS IDENTITY,
  title      varchar(200) NOT NULL,
  content    text NOT NULL DEFAULT '',
  created_by varchar(50) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  use_yn     char(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (region, memo_idn)
);
CREATE INDEX IF NOT EXISTS idx_memo_search ON tb_memo (region, created_at DESC);

-- 2) 일정 알림 (개인 스케줄 — SCADA 알람과 무관)
CREATE TABLE IF NOT EXISTS tb_user_schedule (
  region       varchar(20) NOT NULL,
  schedule_idn bigint GENERATED BY DEFAULT AS IDENTITY,
  title        varchar(200) NOT NULL,
  content      text NOT NULL DEFAULT '',
  alarm_at     timestamptz NOT NULL,
  created_by   varchar(50) NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  notified_at  timestamptz,
  acked_at     timestamptz,
  use_yn       char(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (region, schedule_idn)
);
CREATE INDEX IF NOT EXISTS idx_schedule_due
  ON tb_user_schedule (region, created_by, alarm_at)
  WHERE acked_at IS NULL AND use_yn = 'Y';

-- 3) 메뉴 등록 — 보고서(M005) 하위
INSERT INTO tb_menu (region, menu_idn, menu_nm, pmenu_idn, app_path, menu_type, menu_idx, use_yn)
VALUES
  ('R01', 'M005-3', '업무 메모', 'M005', '/reports/memo',     'menu', 3, 'Y'),
  ('R01', 'M005-4', '일정 알림', 'M005', '/reports/schedule', 'menu', 4, 'Y')
ON CONFLICT (region, menu_idn) DO UPDATE
  SET menu_nm = EXCLUDED.menu_nm, app_path = EXCLUDED.app_path, use_yn = 'Y';

-- 4) 권한 — 보고서(M005-1 장애 조치 보고서)와 동일 권한 세트에 부여
INSERT INTO tb_auth_menu (region, auth_idn, menu_idn)
SELECT region, auth_idn, m.menu_idn
FROM tb_auth_menu t
CROSS JOIN (VALUES ('M005-3'), ('M005-4')) AS m(menu_idn)
WHERE t.menu_idn = 'M005-1'
ON CONFLICT DO NOTHING;
