-- 0106: 운영자 간 1:1 채팅 P1 (docs/realtime-comm-spec.md §5.1)
--   tb_user_chat_message / tb_user_chat_read + 메신저 메뉴 M010
-- 롤백:
--   DELETE FROM tb_auth_menu WHERE menu_idn='M010';
--   DELETE FROM tb_menu WHERE menu_idn='M010';
--   DROP TABLE IF EXISTS tb_user_chat_read;
--   DROP TABLE IF EXISTS tb_user_chat_message;

-- 1) 메시지 — room_id: 'dm:<a>|<b>' (정렬) 또는 'all'
CREATE TABLE IF NOT EXISTS tb_user_chat_message (
  region     varchar(20) NOT NULL,
  msg_idn    bigint GENERATED BY DEFAULT AS IDENTITY,
  room_id    varchar(120) NOT NULL,
  sender_id  varchar(50) NOT NULL,
  content    text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  use_yn     char(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (region, msg_idn)
);
CREATE INDEX IF NOT EXISTS idx_user_chat_room
  ON tb_user_chat_message (region, room_id, msg_idn DESC);

-- 2) 읽음 위치 — unread 뱃지 계산용
CREATE TABLE IF NOT EXISTS tb_user_chat_read (
  region        varchar(20) NOT NULL,
  room_id       varchar(120) NOT NULL,
  user_id       varchar(50) NOT NULL,
  last_read_idn bigint NOT NULL DEFAULT 0,
  updated_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (region, room_id, user_id)
);

-- 3) 메뉴 — 톱레벨 메신저
INSERT INTO tb_menu (region, menu_idn, menu_nm, pmenu_idn, app_path, menu_type, menu_idx, use_yn)
VALUES ('R01', 'M010', '메신저', NULL, '/messenger', 'menu', 10, 'Y')
ON CONFLICT (region, menu_idn) DO UPDATE
  SET menu_nm = EXCLUDED.menu_nm, app_path = EXCLUDED.app_path, use_yn = 'Y';

-- 4) 권한 — 보고서(M005-1)와 동일 권한 세트 (전 운영자)
INSERT INTO tb_auth_menu (region, auth_idn, menu_idn)
SELECT region, auth_idn, 'M010' FROM tb_auth_menu WHERE menu_idn = 'M005-1'
ON CONFLICT DO NOTHING;
