-- 0108: 메신저 P3 — 운영자 1:1 음성 통화 시그널링 (docs/realtime-comm-spec.md §5.4)
--   REST 폴링 시그널링 + 통화 이력 겸용. SDP 는 non-trickle (gathering 완료 후 교환)
-- 롤백:
--   DROP TABLE IF EXISTS tb_call_session;

CREATE TABLE IF NOT EXISTS tb_call_session (
  region      varchar(20) NOT NULL,
  call_id     bigint GENERATED BY DEFAULT AS IDENTITY,
  caller_id   varchar(50) NOT NULL,
  callee_id   varchar(50) NOT NULL,
  -- ringing → accepted / rejected / canceled / missed → ended
  status      varchar(10) NOT NULL DEFAULT 'ringing',
  offer_sdp   text NOT NULL,
  answer_sdp  text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  answered_at timestamptz,
  ended_at    timestamptz,
  end_by      varchar(50),
  PRIMARY KEY (region, call_id)
);
CREATE INDEX IF NOT EXISTS idx_call_incoming
  ON tb_call_session (region, callee_id, created_at DESC)
  WHERE status = 'ringing';
