-- 0112: 3~4인 회의 통화 (풀메시) — docs/realtime-comm-spec.md §7
--   방 + 참가자 + 쌍별 SDP 사서함. 음성 v1.
-- 롤백:
--   DROP TABLE IF EXISTS tb_conf_signal;
--   DROP TABLE IF EXISTS tb_conf_member;
--   DROP TABLE IF EXISTS tb_conf_call;

CREATE TABLE IF NOT EXISTS tb_conf_call (
  region     varchar(20) NOT NULL,
  conf_id    bigint GENERATED BY DEFAULT AS IDENTITY,
  host_id    varchar(50) NOT NULL,
  status     varchar(10) NOT NULL DEFAULT 'active',   -- active | ended
  created_at timestamptz NOT NULL DEFAULT now(),
  ended_at   timestamptz,
  PRIMARY KEY (region, conf_id)
);

CREATE TABLE IF NOT EXISTS tb_conf_member (
  region       varchar(20) NOT NULL,
  conf_id      bigint NOT NULL,
  user_id      varchar(50) NOT NULL,
  -- invited → joined / rejected / missed → left
  status       varchar(10) NOT NULL DEFAULT 'invited',
  invited_at   timestamptz NOT NULL DEFAULT now(),
  joined_at    timestamptz,
  left_at      timestamptz,
  last_poll_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (region, conf_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_conf_member_incoming
  ON tb_conf_member (region, user_id) WHERE status = 'invited';

-- 쌍별 SDP 사서함 (풀메시 — 신규 합류자가 기존 참가자 전원에게 offer)
CREATE TABLE IF NOT EXISTS tb_conf_signal (
  region      varchar(20) NOT NULL,
  sig_id      bigint GENERATED BY DEFAULT AS IDENTITY,
  conf_id     bigint NOT NULL,
  from_user   varchar(50) NOT NULL,
  to_user     varchar(50) NOT NULL,
  kind        varchar(10) NOT NULL,   -- offer | answer
  sdp         text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  consumed_at timestamptz,
  PRIMARY KEY (region, sig_id)
);
CREATE INDEX IF NOT EXISTS idx_conf_signal_inbox
  ON tb_conf_signal (region, conf_id, to_user) WHERE consumed_at IS NULL;
