-- 0113: 그룹 채팅 — 다중 초대 대화방 (docs/realtime-comm-spec.md §5.1 확장)
--   room_id = 'grp:<group_id>'. 메시지·읽음은 기존 tb_user_chat_* 재사용.
-- 롤백:
--   DROP TABLE IF EXISTS tb_chat_group_member;
--   DROP TABLE IF EXISTS tb_chat_group;

CREATE TABLE IF NOT EXISTS tb_chat_group (
  region     varchar(20) NOT NULL,
  group_id   bigint GENERATED BY DEFAULT AS IDENTITY,
  title      varchar(100) NOT NULL,
  created_by varchar(50) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (region, group_id)
);

CREATE TABLE IF NOT EXISTS tb_chat_group_member (
  region    varchar(20) NOT NULL,
  group_id  bigint NOT NULL,
  user_id   varchar(50) NOT NULL,
  joined_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (region, group_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_chat_group_member_user
  ON tb_chat_group_member (region, user_id);
