-- 0133_incident_report.sql
-- 상황보고 1보/2보 (docs/incident-report-spec.md — 로드맵 D P1)
--
-- 저장을 tb_report/tb_report_item 에 얹지 않는 이유: 그 테이블은 장애·점검
-- "항목 리스트" 구조고, 상황보고는 "서술 섹션 문서"(개요/상황/조치/전망)다.
-- 로드맵 D 의 재사용 포인트는 저장 스키마가 아니라 출력(브라우저 인쇄
-- self-contained HTML)과 편집→확정 흐름이다.
--
-- 차수(1보/2보)는 parent_id 자기참조 — 2보는 1보를 부모로 갖는다.
-- "영향 세대수"는 자동 채움하지 않는다 — 세대·급수인구 데이터가 DB 에
-- 없다 (2026-07-28 조사). sections.impact 에 담당자가 기입한다.
--
-- 롤백: 파일 하단 ROLLBACK 블록

BEGIN;

CREATE TABLE IF NOT EXISTS tb_incident_report (
    region        varchar(20)  NOT NULL,
    incident_id   bigint       GENERATED BY DEFAULT AS IDENTITY,
    parent_id     bigint,                    -- 1보=NULL, 2보 이후=직전 보 id
    bulletin_no   integer      NOT NULL DEFAULT 1,   -- 1=1보, 2=2보 …
    title         varchar(200) NOT NULL,
    sitename      varchar(100) NOT NULL,
    facilitytype  varchar(50)  NOT NULL DEFAULT '',
    occurred_at   timestamptz  NOT NULL,     -- 사고 발생 시각 (1보에서 확정)
    -- 서술 섹션 (jsonb): overview 개요 / situation 상황·경과 / actions 조치
    -- / impact 영향(세대수 등 수동) / outlook 향후 계획 / contact 보고자
    sections      jsonb        NOT NULL DEFAULT '{}'::jsonb,
    status        varchar(10)  NOT NULL DEFAULT 'draft'
                  CHECK (status IN ('draft', 'final')),
    created_by    varchar(50)  NOT NULL,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),
    finalized_at  timestamptz,
    PRIMARY KEY (region, incident_id)
);

CREATE INDEX IF NOT EXISTS idx_incident_report_list
    ON tb_incident_report (region, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_incident_report_parent
    ON tb_incident_report (region, parent_id) WHERE parent_id IS NOT NULL;

COMMENT ON TABLE tb_incident_report IS
  '상황보고 1보/2보 공문 초안 (incident-report-spec). 자동 채움은 생성 시점 1회, 이후 담당자 편집이 정본';

-- 메뉴 M005-6 — 보고서 그룹
INSERT INTO tb_menu (region, menu_idn, menu_nm, pmenu_idn, app_path, menu_type, menu_idx, use_yn)
SELECT m.region, 'M005-6', '상황보고 (1·2보)', 'M005', '/reports/incident', 'menu', 6, 'Y'
FROM tb_menu m WHERE m.menu_idn = 'M005'
ON CONFLICT (region, menu_idn) DO NOTHING;

INSERT INTO tb_auth_menu (region, auth_idn, menu_idn)
SELECT DISTINCT a.region, a.auth_idn, 'M005-6'
FROM tb_auth_menu a WHERE a.menu_idn = 'M005-1'
ON CONFLICT DO NOTHING;

COMMIT;

-- =============================================================================
-- ROLLBACK
-- =============================================================================
-- BEGIN;
-- DELETE FROM tb_auth_menu WHERE menu_idn = 'M005-6';
-- DELETE FROM tb_menu      WHERE menu_idn = 'M005-6';
-- DROP TABLE IF EXISTS tb_incident_report;
-- COMMIT;
