-- 0136_site_knowledge.sql
-- 현장 지식 카드 (docs/site-knowledge-spec.md — 로드맵 B P1)
--
-- 운영자 암묵지를 카드 단위로 등록·조회한다. P1 은 조회·기록 계층만 —
-- 알람 생성·해제 어디에도 개입하지 않는다 (억제 반영은 통합 억제 로그
-- 설계 후 P2. 안전 임계 HH/LL 은 그때도 카드로 끌 수 없다 — 부록 B.2).
--
-- revision 테이블: 수정·삭제 전 스냅샷 보존 — 공공 납품 감사 추적.
-- 카드 삭제는 허용하되 이력은 남는다.
--
-- 롤백: 파일 하단 ROLLBACK 블록

BEGIN;

CREATE TABLE IF NOT EXISTS tb_site_knowledge (
    region        varchar(20)  NOT NULL,
    knowledge_id  bigint       GENERATED BY DEFAULT AS IDENTITY,
    -- 유형 4종 (로드맵 부록 B.3 — '연락 체계'는 비상연락처가 정본이라 제외)
    k_type        varchar(20)  NOT NULL
                  CHECK (k_type IN ('periodic', 'trait', 'exception', 'procedure')),
    title         varchar(200) NOT NULL,
    -- {sitenames[], facilitytypes[], tagsns[], alarm_categories[]}
    -- 지정 필드 간 AND, 배열 내 OR. 최소 1개 필드 필수 (전역 카드 금지)
    target_refs   jsonb        NOT NULL DEFAULT '{}'::jsonb,
    -- {weekdays[1~7 ISO], time_from "HH:MM", time_to, months[1~12]} — 비우면 상시
    conditions    jsonb        NOT NULL DEFAULT '{}'::jsonb,
    description   text         NOT NULL DEFAULT '',
    valid_from    timestamptz,
    valid_until   timestamptz,
    status        varchar(10)  NOT NULL DEFAULT 'draft'
                  CHECK (status IN ('draft', 'active', 'retired')),
    created_by    varchar(50)  NOT NULL,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_by    varchar(50),
    updated_at    timestamptz  NOT NULL DEFAULT now(),
    PRIMARY KEY (region, knowledge_id)
);

CREATE INDEX IF NOT EXISTS idx_site_knowledge_list
    ON tb_site_knowledge (region, status, updated_at DESC);

-- 변경 전 스냅샷 — "이 지식을 누가 언제 왜 바꿨나"
CREATE TABLE IF NOT EXISTS tb_site_knowledge_revision (
    region        varchar(20) NOT NULL,
    revision_id   bigint      GENERATED BY DEFAULT AS IDENTITY,
    knowledge_id  bigint      NOT NULL,
    action        varchar(10) NOT NULL CHECK (action IN ('update', 'delete')),
    snapshot      jsonb       NOT NULL,   -- 변경 직전 카드 전체
    changed_by    varchar(50) NOT NULL,
    changed_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (region, revision_id)
);

CREATE INDEX IF NOT EXISTS idx_site_knowledge_rev
    ON tb_site_knowledge_revision (region, knowledge_id, changed_at DESC);

COMMENT ON TABLE tb_site_knowledge IS
  '현장 지식 카드 (site-knowledge-spec, 로드맵 B P1). 조회·기록 계층 — 알람 억제 없음';
COMMENT ON TABLE tb_site_knowledge_revision IS
  '지식 카드 변경 이력 — 수정·삭제 전 스냅샷 (감사 추적)';

-- 메뉴 M006-8 — 위기대응 그룹 (경보를 판단하는 사람들의 자리)
INSERT INTO tb_menu (region, menu_idn, menu_nm, pmenu_idn, app_path, menu_type, menu_idx, use_yn)
SELECT m.region, 'M006-8', '현장 지식', 'M006', '/crisis/site-knowledge', 'menu', 8, 'Y'
FROM tb_menu m WHERE m.menu_idn = 'M006'
ON CONFLICT (region, menu_idn) DO NOTHING;

INSERT INTO tb_auth_menu (region, auth_idn, menu_idn)
SELECT DISTINCT a.region, a.auth_idn, 'M006-8'
FROM tb_auth_menu a WHERE a.menu_idn = 'M006-1'
ON CONFLICT DO NOTHING;

COMMIT;

-- =============================================================================
-- ROLLBACK
-- =============================================================================
-- BEGIN;
-- DELETE FROM tb_auth_menu WHERE menu_idn = 'M006-8';
-- DELETE FROM tb_menu      WHERE menu_idn = 'M006-8';
-- DROP TABLE IF EXISTS tb_site_knowledge_revision;
-- DROP TABLE IF EXISTS tb_site_knowledge;
-- COMMIT;
